### ISSUE TITLE
新規Activitie作成処理

### ISSUE THREAD

**Issue by claustra01** [claustra01/hackz-nokogiri-frontend#11]

**Comment by TOMOQ1024** [comment]
b6f475fef0ee9d3bf52259356e3df3408997dc3b
5677908910461f0729a62488111b4db864e8c2e9

**Comment by TOMOQ1024** [comment]
post
/activitie (活動の新規作成)
{
   "name": "XXX",
   "dateTime": "XXX",
   "place": "XXX",
   "misc": "XXX" (null許容しないのでない場合は空文字列で),
   "recordId": "XXX"
}

**Comment by claustra01** [comment]
13feea266ccdd3e8a3f0dd229ca033f590fe90f5
