### ISSUE TITLE
activities.tsx データ処理

### ISSUE THREAD

**Issue by claustra01** [claustra01/hackz-nokogiri-frontend#4]
参考: https://github.com/claustra01/hackz-nokogiri-backend/issues/6

**Comment by TOMOQ1024** [comment]
dc05db702026dd6ce9ee5818e82898308c928565

**Comment by claustra01** [comment]
ダークモード対応どうするか

**Comment by TOMOQ1024** [comment]
a206fdc6480736ac754b2d03b6794adfa4188df3
